"""add_refresh_token_session_metadata

Revision ID: 750e9fc7a2a6
Revises: caf7d1fdd0f7
Create Date: 2026-03-18 04:40:22.522146

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '750e9fc7a2a6'
down_revision: Union[str, None] = 'caf7d1fdd0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=100), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    # ### end Alembic commands ###
