"""add_ingestion_pipeline_tables

Revision ID: caf7d1fdd0f7
Revises: e7d2db17e25c
Create Date: 2026-03-18 03:53:57.585721

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'caf7d1fdd0f7'
down_revision: Union[str, None] = 'e7d2db17e25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_saved', sa.Integer(), nullable=False),
    sa.Column('items_deduplicated', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_project_id'), 'crawl_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_source_id'), 'crawl_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('final_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title_hash', sa.String(length=64), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_documents_project_id'), 'raw_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_source_id'), 'raw_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_text_hash'), 'raw_documents', ['text_hash'], unique=False)
    op.create_index(op.f('ix_raw_documents_title_hash'), 'raw_documents', ['title_hash'], unique=False)
    op.create_index(op.f('ix_raw_documents_url_hash'), 'raw_documents', ['url_hash'], unique=False)
    op.create_table('source_fetch_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.String(length=1024), nullable=True),
    sa.Column('last_url', sa.String(length=1000), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_fetch_states_source_id'), 'source_fetch_states', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_fetch_states_source_id'), table_name='source_fetch_states')
    op.drop_table('source_fetch_states')
    op.drop_index(op.f('ix_raw_documents_url_hash'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_title_hash'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_text_hash'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_source_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_project_id'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_source_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_project_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
